title: "Dafuq is that"
email: mitatoto1997@gmail.com
baseurl: /

# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-uk'

# Website info
name: 'Dafuq is that'
description: "Product Management meets PKM"

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]